### ISSUE TITLE
Crash on saving

### ISSUE THREAD

**Issue by concommie** [ScottyThePilot/hoi4_province_editor#9] opened 2023-10-15 01:27 UTC
Hi, been using this tool for the past few months and suddenly there's a crash when I try to save. 

Crash log: 
`The application panicked (crashed).
Message:  no entry found for key
Location: src\app\map\bridge.rs:399

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: BaseThreadInitThunk
    at <unknown source file>
 2: RtlUserThreadStart
    at <unknown source file>`

max-undo-states: 24
preserve-ids: true
generate-coastal-on-save: false
I am using a few added custom terrains.

**Comment by concommie** [comment] 2023-10-15 02:52
I figured it out, has to do with moving a lot of provinces around with adjacencies already defined and having them break. Removed all the relevant adjacencies and it worked

**Comment by ScottyThePilot** [comment] 2023-10-16 02:41
I believe this is a bug. It appears to be caused by the [through province](https://hoi4.paradoxwikis.com/Map_modding#Adjacencies) (currently not assignable through HOI4PE) of an already-defined adjacency becoming deleted, which is not handled.

**Comment by ScottyThePilot** [comment] 2023-10-16 04:59
This is fixed in the latest release.

**Closed by ScottyThePilot** 2023-10-16 04:59 UTC
